# Generated by Django 5.2.11 on 2026-08-14 07:10

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('customer_name', models.CharField(max_length=120)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=10)),
                ('customer_latitude', models.FloatField(blank=True, null=True)),
                ('customer_longitude', models.FloatField(blank=True, null=True)),
                ('distance_km', models.FloatField(blank=True, null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('new', 'New'), ('confirmed', 'Confirmed'), ('completed', 'Completed')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StoreConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(default='Demo Fashion Store', max_length=120)),
                ('tagline', models.CharField(default='Style That Speaks For You', max_length=200)),
                ('hero_subtext', models.CharField(default='Discover our latest collection of fashion, curated for every occasion.', max_length=300)),
                ('phone', models.CharField(default='+91 90000 00000', max_length=30)),
                ('address', models.CharField(default='Store Address, City, State, PIN', max_length=255)),
                ('instagram_url', models.URLField(default='https://instagram.com/')),
                ('instagram_handle', models.CharField(default='@demofashionstore', max_length=60)),
                ('owner_name', models.CharField(default='Store Owner', max_length=120)),
                ('founded_year', models.PositiveIntegerField(default=2015)),
                ('opening_hours', models.CharField(default='Mon - Sat: 10:00 AM - 9:00 PM  |  Sun: 11:00 AM - 7:00 PM', max_length=255)),
                ('about_text', models.TextField(default='Since 2015, Demo Fashion Store has been serving our community with carefully selected fashion for every occasion. From everyday essentials to festive collections, we focus on quality, style and personal service.')),
                ('festive_offer_title', models.CharField(blank=True, default='FESTIVE SPECIAL', max_length=120)),
                ('festive_offer_text', models.CharField(blank=True, default='Shop for ₹1,000 or more and receive a complimentary Rakhi & Sweet.', max_length=255)),
                ('festive_offer_active', models.BooleanField(default=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='store_config/')),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='store_config/')),
                ('owner_image', models.ImageField(blank=True, null=True, upload_to='store_config/')),
                ('store_exterior_image', models.ImageField(blank=True, null=True, upload_to='store_config/')),
                ('store_interior_image', models.ImageField(blank=True, null=True, upload_to='store_config/')),
                ('new_collection_image', models.ImageField(blank=True, null=True, upload_to='store_config/')),
                ('festival_display_image', models.ImageField(blank=True, null=True, upload_to='store_config/')),
                ('store_latitude', models.FloatField(default=17.2473)),
                ('store_longitude', models.FloatField(default=80.1514)),
                ('delivery_radius_km', models.FloatField(default=10.0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Store configuration',
                'verbose_name_plural': 'Store configuration',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=170, unique=True)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('stock_quantity', models.PositiveIntegerField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='store.category')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=150)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='store.order')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.product')),
            ],
        ),
    ]
